linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - varnamelen # useless
    - tagliatelle # Breaking: 'Rule' tag -> 'rule'

issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
        - exhaustivestruct

linters-settings:
  cyclop:
    max-complexity: 11
