displayName: Header transformation
type: middleware

import: github.com/tommoulard/htransformation

summary: 'Transform some headers with some other ones, see https://github.com/traefik/traefik/issues/6047'

testData:
  Rules:
    - Rule:
      Name: 'Header transformation'
      Header: 'X-Traefik-*'
      Value: 'X-custom'
      Type: 'Rename'
    - Rule:
      Name: 'Header addition'
      Header: 'X-Custom'
      Value: 'True'
      Type: 'Set'
    - Rule:
      Name: 'Header addition'
      Header: 'X-Custom-2'
      Value: 'True'
      Type: 'Set'
    - Rule:
      Name: 'Header deletion'
      Header: 'X-forward'
      Type: 'Del'
    - Rule:
      Name: 'Header join'
      Header: 'X-Custom-2'
      Sep: ','
      Values:
        - 'False'
        - 'Idk'
      Type: 'Join'